# Generated by Django 3.2.3 on 2021-06-02 00:54

from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('avatar', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='helpdesk/')),
                ('numAp', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11)),
                ('phone', models.CharField(max_length=11)),
                ('isUser', models.BooleanField()),
                ('isAdmin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='helpdesk/')),
                ('problem', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('AB', 'Em aberto'), ('AN', 'Em análise'), ('CO', 'Concluído'), ('RE', 'Rejeitado')], default='AB', max_length=2)),
                ('priority', models.CharField(choices=[('BA', 'Baixa'), ('ME', 'Media'), ('AL', 'Alta')], max_length=2)),
                ('numApOccurrence', models.IntegerField()),
                ('description', models.TextField()),
                ('feedbackManager', models.TextField()),
                ('openDate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
