# Generated by Django 3.2.3 on 2021-06-03 02:14

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210602_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='files',
            field=models.FileField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='helpdesk/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='helpdesk/'),
        ),
    ]
