# Generated by Django 3.2.3 on 2021-06-03 03:58

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210602_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='helpdesk/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='cpf',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='users',
            name='floor',
            field=models.IntegerField(blank=True),
        ),
    ]
