# Generated by Django 3.2.3 on 2021-06-03 04:06

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210603_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='files',
            field=models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='helpdesk/'),
        ),
    ]
