# Generated by Django 3.2.3 on 2021-06-03 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_tickets_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notificationType',
            field=models.CharField(choices=[('Manutenção', 'Manutenção'), ('Mudança', 'Mudança'), ('Reunião', 'Reunião'), ('Informações Gerais', 'Informações Gerais'), ('Outros', 'Outros')], default='Informações Gerais', max_length=30),
        ),
        migrations.AlterField(
            model_name='problems',
            name='problemType',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='feedbackManager',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='priority',
            field=models.CharField(choices=[('Baixa', 'Baixa'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.problems', to_field='problemType'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.CharField(choices=[('Em aberto', 'Em aberto'), ('Em análise', 'Em análise'), ('Concluído', 'Concluído'), ('Rejeitado', 'Rejeitado')], default='Em aberto', max_length=30),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.users'),
        ),
    ]
