# Generated by Django 3.2.3 on 2021-06-04 16:12

from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210604_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(permissions=(gdstorage.storage.GoogleDriveFilePermission(gdstorage.storage.GoogleDrivePermissionRole['READER'], gdstorage.storage.GoogleDrivePermissionType['USER'], 'condominioquintahelpdesk@gmail.com'),)), upload_to='helpdesk/')),
            ],
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notificationType',
            field=models.CharField(choices=[('MA', 'Manutenção'), ('MU', 'Mudança'), ('RE', 'Reunião'), ('IG', 'Informações Gerais'), ('OU', 'Outros')], default='IG', max_length=2),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='priority',
            field=models.CharField(choices=[('BA', 'Baixa'), ('ME', 'Media'), ('AL', 'Alta')], max_length=2),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.CharField(choices=[('AB', 'Em aberto'), ('AN', 'Em análise'), ('CO', 'Concluído'), ('RE', 'Rejeitado')], default='AB', max_length=2),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.files'),
        ),
    ]
