# Generated by Django 3.2.3 on 2021-06-04 19:25

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210604_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='files',
            field=models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(permissions=(gdstorage.storage.GoogleDriveFilePermission(gdstorage.storage.GoogleDrivePermissionRole['READER'], gdstorage.storage.GoogleDrivePermissionType['USER'], 'condominioquintahelpdesk@gmail.com'),)), upload_to='helpdesk/'),
        ),
    ]
