# Generated by Django 3.2.3 on 2021-06-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210604_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='isUser',
            field=models.BooleanField(default=True),
        ),
    ]
