# Generated by Django 3.2.3 on 2021-06-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210610_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowPriority', models.CharField(default='#08c70b', max_length=30)),
                ('mediumPriority', models.CharField(default='#eda915', max_length=30)),
                ('highPriority', models.CharField(default='#ff0000', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.RemoveField(
            model_name='users',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notificationType',
            field=models.CharField(choices=[('MA', 'Manutenção'), ('MU', 'Mudança'), ('RE', 'Reunião'), ('IG', 'Informações Gerais'), ('OU', 'Outros')], default='IG', max_length=2),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='priority',
            field=models.CharField(choices=[('BA', 'Baixa'), ('ME', 'Media'), ('AL', 'Alta')], max_length=2),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.CharField(choices=[('AB', 'Em aberto'), ('AN', 'Em análise'), ('CO', 'Concluído'), ('RE', 'Rejeitado')], default='AB', max_length=2),
        ),
        migrations.AlterField(
            model_name='users',
            name='numAp',
            field=models.IntegerField(),
        ),
    ]
