# Generated by Django 3.2.3 on 2021-06-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210610_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notificationType',
            field=models.CharField(choices=[('Manutenção', 'Manutenção'), ('Mudança', 'Mudança'), ('Reunião', 'Reunião'), ('Informações Gerais', 'Informações Gerais'), ('Outros', 'Outros')], default='Informações Gerais', max_length=50),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='priority',
            field=models.CharField(choices=[('Baixa', 'Baixa'), ('Media', 'Media'), ('Alta', 'Alta')], default='Baixa', max_length=50),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.CharField(choices=[('Em aberto', 'Em aberto'), ('Em análise', 'Em análise'), ('Concluído', 'Concluído'), ('Rejeitado', 'Rejeitado')], default='Em aberto', max_length=50),
        ),
    ]
