# Generated by Django 3.2.4 on 2021-06-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_historicaltickets_ticketschangehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketsChangeHistory',
        ),
    ]
